name: Wonderkids FM21 Scraper

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Install Playwright
        run: |
          python -m playwright install chromium

      - name: Run scraper
        run: |
          python scraper/scrape.py

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: |
            players.json
            
      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: |
            debug.html
            debug.png

            
      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
        name: result
        path: requests.txt
